### ISSUE TITLE
type argument not working 

### ISSUE THREAD

**Issue by ggloor** [egr95/R-codacore#5]
Hi 

I'm trying this tool out on a couple of datasets and this is happening:

 model.24=codacore(t(d.24), tf.conds, type = "balances" )
Error in codacore(t(d.24), tf.conds, type = "balances") : 
  unused argument (type = "balances")

If I leave the type argument blank it works just fine

**Comment by egr95** [comment]
Hi Greg,

Thanks a lot for pointing this out - the argument should read `logRatioType = "balances"`, instead of just `type = "balances"`. I had updated this in the code and in the [guide](https://egr95.github.io/R-codacore/guide.html), but not in the [README](https://github.com/egr95/R-codacore), which I presume is where you saw this signature. Fixed now.

Thanks!

P.S: if you're interested in learning predictive Summed-Log-Ratios as well as balances, try `logRatioType = "SLR"`.
Also, I notice you are passing a response vector named `tf.conds`. Might this name be because the response vector is a Tensorflow object? This is totally fine, but note that this vector can just be a regular numeric vector (binary or continuous). In other words, it should not _need_ to be converted to Tensorflow in order to make things work. I'm sure you're already aware, but just in case!
